### ISSUE TITLE
multi wolrd

### ISSUE THREAD

**Issue by ctw452002** [CzechPMDevs/MyStats#10]
is this support multi world like if we go to main world the hud will be displayed if we go to second world it will disappear

**Comment by GamakCZ** [comment]
yes, add world to ['popupWorlds'](https://github.com/CzechPMDevs/MyStats/blob/master/MyStats/resources/config.yml#L122) or ['tipWorlds'](https://github.com/CzechPMDevs/MyStats/blob/master/MyStats/resources/config.yml#L127) in config.yml
