### ISSUE TITLE
Still not saving

### ISSUE THREAD

**Issue by SuperAlecs** [CzechPMDevs/MyStats#12]
Hello the stats still not saving, to reproduce it try to kill or death, restart the server, try to kill or death again, quit and rejoin and your stats won't save, I'm using 1.4.11 version of the plugin

**Comment by GamakCZ** [comment]
Is some error in console?

**Comment by SuperAlecs** [comment]
Nothing

**Comment by GamakCZ** [comment]
I can't reproduce it
