### ISSUE TITLE
update economy in mystats

### ISSUE THREAD

**Issue by SoflyTtv** [CzechPMDevs/MyStats#13]
https://github.com/CzechPMDevs/MyStats/tree/master/MyStats/src/mystats/economy
it says 0 for the new update of economyAPI

**Comment by SoflyTtv** [comment]
and can u add more stuff Plz I will be plzzz and add suffix and prefix

**Comment by SoflyTtv** [comment]
yea the economyAPI change in code so update it plz

**Comment by GamakCZ** [comment]
EconomyAPI works, you probably forgot to change economy in config to EconomyAPI
