### ISSUE TITLE
Money status?

### ISSUE THREAD

**Issue by asyncthreading** [CzechPMDevs/MyStats#4]
můžete přidat prosím economyapi podporu?

**Comment by GamakCZ** [comment]
Byla přidána už dávno... :) 

https://github.com/CzechPMDevs/MyStats/blob/master/MyStats/resources/config.yml#L38
https://github.com/CzechPMDevs/MyStats/blob/master/MyStats/resources/config.yml#L21
https://github.com/CzechPMDevs/MyStats/blob/master/MyStats/src/MyStats/Economy/EconomyManager.php#L33
