### ISSUE TITLE
ItemID

### ISSUE THREAD

**Issue by servantthought** [CzechPMDevs/MyStats#8]
Most worked great but %itemid and %itemname are not displayed. Do I need an additional  plugin to make it work... %itemid only displays as itemid and %itemname displays  itemname instead. I just noticed %money is showing 0 but when  I type /mymoney it shows my true balance  of 80789. Also coordinates xyz x=y's value and last but most likely least IP shows 0.0.0.0 
These are the only problems I found do I need additional plugins... ? I have EconomyAPI plugin and its set to true in config.yml for the money problem...

**Comment by GamakCZ** [comment]
fixed
